@startuml
'https://plantuml.com/class-diagram

enum SubjectType {
Base
Optional
}


struct Subject {
+ name : string
+ type : SubjectType
}

SubjectType <--* Subject

struct Date {
+ day : int
+ month : int
+ year : int
}

enum StatusTeacher {
Works
Fired
OnHoliday
OnSickLeave
}

struct Teacher {
+ first_name : string
+ last_name : string
+ patronymic : string
+ date_of_birth : Date
+ faculty : string
+ department : string
+ date_of_employment : Date
+ date_of_dismissal : Date
+ status : StatusTeacher
+ subjects : Subject[]
}

Subject <--* Teacher
StatusTeacher <--* Teacher
Date <--* Teacher

struct Student {
+ first_name : string
+ last_name : string
+ patronymic : string
+ faculty : string
+ date_of_receipt : Date
+ date_of_deduction : Date
+ status : StatusStudent
+ subjects : Subject[]
+ journal : map<subject.id,marks[]>;
}

enum StatusStudent {
educate
dismissed
AcademHoliday
}

Subject <--* Student
StatusStudent <--* Student
Date <--* Student

@enduml