@startuml
'https://plantuml.com/class-diagram

enum SubjectType {
Base
Optional
}

SubjectType <--* Subject
class Subject {
+ name : string
+ type : SubjectType
}

class Date {
+ day : int
+ month : int
+ year : int
}

enum StatusTeacher {
Works
Fired
OnHoliday
OnSickLeave
}

Subject <--* Teacher
StatusTeacher <--* Teacher
Date <--* Teacher
class Teacher {
+ first_name : string
+ last_name : string
+ patronymic : string
+ date_of_birth : Date
+ faculty : string
+ department : string
+ date_of_employment : Date
+ date_of_dismissal : Date
+ status : StatusTeacher
+ subjects : Subject[]
}

@enduml